### PR TITLE
Update README.md and sync README.ja.md to README.md

### PR DESCRIPTION
**Pull request by kenjis**

### CODE REVIEW

**Comment by koriym** [comment]
:+1:

**Comment by kenjis** [comment]
I have found some errors in README.
1. [Matcher](http://bearsunday.github.io/builds/Ray.Aop/api/class-Ray.Aop.Matchable.html) and [MethodInterceptors](http://bearsunday.github.io/builds/Ray.Aop/api/class-Ray.Aop.MethodInterceptor.html) are now 404.
2. A part of sample code is still out-of-dated. It does not work and the code does not match the explanation.

About 1, are there new pages to link?

About 2, in the buttom of _Example: Forbidding method calls on weekends_, there are Fatal error `RuntimeException:` and `Call Stack:`. But the code has try catch block, so you don't see the error and the call stack. And the call stack seems to be out-of-dated.

The current call stack is like:

```
Call Stack:
    0.0007     227944   1. {main}() .../test.php:0
    0.1098    1894328   2. RealBillingService_F5ORKGQ->chargeOrder() .../test.php:26
    0.1113    1917072   3. Ray\Aop\ReflectiveMethodInvocation->proceed() .../tmp/RealBillingService_F5ORKGQ.php:19
    0.1113    1917416   4. WeekendBlocker->invoke() .../vendor/ray/aop/src/ReflectiveMethodInvocation.php:80
```

Do you need to show call stack?

**Comment by koriym** [comment]
@kenjis thanks for the report.

> Matcher and MethodInterceptors are now 404.

Probably is the source in Guthu enough ?

> About 2, in the bottom of Example

seems ok to remove trace code.

Can I have PR ?

**Comment by kenjis** [comment]
Yup, I'm going to send PR later.

**Pull request merged**
