### PR TITLE
[WIP] make AnnotationReader injectable

### PR DESCRIPTION
**Pull request by izayoi256**
``` php
$reader = new CachedReader(
    new AnnotationReader(),
    new ApcCache()
);

// $reader is optional.
// If null was passed, Doctrine\Common\Annotations\AnnotationReader is instantiated automatically.
$compiler = new Compiler($dir, $reader);

```

### CODE REVIEW

**Comment by izayoi256** [comment]
# Benchmark

Using Ray.Aop through [ytake/Laravel-Aspect](https://github.com/ytake/Laravel-Aspect)

## Default AnnotationReader

範囲を選択_024

## CachedReader with FilesystemCache

範囲を選択_023

**Comment by koriym** [comment]
Question:

`Compiler` is for the development (not for the production). Do we really need the high performance of annotation reading ?

**Comment by izayoi256** [comment]
Even if the code was already compiled, Compiler::compile() and AnnotationReader::getXxxAnnotations() are called each time. That's what I understand, right?

https://gist.github.com/izayoi256/8956206659a33982d4ec5c353a65c5af#file-06-cached-php-L31

Stack traces of AnnotationReader invocation: 
```
CodeGen.php:116, Ray\Aop\CodeGen->getClassAnnotation()
CodeGen.php:145, Ray\Aop\CodeGen->getAopProps()
CodeGen.php:70, Ray\Aop\CodeGen->generate()
Compiler.php:109, Ray\Aop\Compiler->requireFile()
Compiler.php:82, Ray\Aop\Compiler->compile()
Compiler.php:61, Ray\Aop\Compiler->newInstance()
06-cache.php:31, {main}()
```

```
CodeGen.php:162, Ray\Aop\CodeGen->getMethodAnnotations()
CodeGen.php:140, Ray\Aop\CodeGen->getAopProps()
CodeGen.php:70, Ray\Aop\CodeGen->generate()
Compiler.php:109, Ray\Aop\Compiler->requireFile()
Compiler.php:82, Ray\Aop\Compiler->compile()
Compiler.php:61, Ray\Aop\Compiler->newInstance()
06-cache.php:31, {main}()
```

**Comment by izayoi256** [comment]
If you don't like constructor injection, I will rewrite the code with ```public function setAnnotationReader(Reader $reader)```.

**Comment by koriym** [comment]
>  Compiler::compile() and AnnotationReader::getXxxAnnotations() are called each time. 

I mean `Compiler::compile()` should not be called in the production.

(Constructor injections is fine.)

**Comment by koriym** [comment]
I read README again, And I found it does not explain about this well. Sorry.🙇🏻‍♂️Let me give some time to re-think about this.

**Comment by izayoi256** [comment]
Better solution #116

**Pull request closed without merging**
